export default {
  colors: {
    primary: "#181030",
    primaryLight: "#E3DAFF",
    secondary: "#ED8839",
    secondary_light: "#FBE7D7",
    success: "#449666",
    white: "#FFFFFF",
    background: "#FFFFFF",
    backgroundDark: "#272627",
    black: "#010104",
    gray: "#6E6C6F",
    lightGray: "#ECE8ED",
    veryLightGray: "#F8F8F8",
    error: "#ED4E4E",
  },
  fonts: {
    blackItalic: "MontserratBlackItalic",
    bold: "MontserratBold",
    boldItalic: "MontserratBoldItalic",
    extraBold: "MontserratExtraBold",
    extraBoldItalic: "MontserratExtraBoldItalic",
    extraLight: "MontserratExtraLight",
    extraLightItalic: "MontserratExtraLightItalic",
    italic: "MontserratItalic",
    light: "MontserratLight",
    lightItalic: "MontserratLightItalic",
    medium: "MontserratMedium",
    mediumItalic: "MontserratMediumItalic",
    regular: "MontserratRegular",
    semiBold: "MontserratSemiBold",
    semiBoldItalic: "MontserratSemiBoldItalic",
    thin: "MontserratThin",
    thinItalic: "MontserratThinItalic",
  },
};
